#ifndef INFLUENCECORE_GLOBAL_H
#define INFLUENCECORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INFLUENCECORE_LIBRARY)
#  define INFLUENCECORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define INFLUENCECORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INFLUENCECORE_GLOBAL_H
